replicaCount: 1

image:
  repository: 163880612827.dkr.ecr.eu-west-1.amazonaws.com/demo-app
  tag: "INITIAL_TAG"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
