apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-app
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/yossisp1972/DevOps-GitOps.git
    targetRevision: main
    path: helm/demo-app

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
