name: Demo App CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "app/demo-app/**"
      - ".github/workflows/app-ci.yml"

  pull_request:
    paths:
      - "app/demo-app/**"
      - ".github/workflows/app-ci.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: demo-app

jobs:
  build:
    name: Build and Push Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate image tag
        id: image
        shell: bash
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=$SHORT_SHA" >> "$GITHUB_OUTPUT"
          echo "Image tag: $SHORT_SHA"

      - name: Build Docker image
        working-directory: app/demo-app
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.tag }} \
            .

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.tag }}

      - name: Print image URI
        if: github.event_name != 'pull_request'
        run: |
          echo "Image pushed:"
          echo "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.tag }}"
